name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.4.1'

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build:prod

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' # or any other valid distribution

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive JAR file
      uses: actions/upload-artifact@v3
      with:
        name: build-jar
        path: build/libs/portfolio-web.war

    - name: List build/libs directory
      run: ls -l build/libs/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v3
      with:
        name: build-jar

    - name: List build/libs directory
      run: ls -l build/libs/

    - name: List current directory
      run: ls -l .

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
      run: |
        scp -o StrictHostKeyChecking=no build/libs/portfolio-web.war $VPS_USER@$VPS_HOST:~/divij_tech/portfolio-web.war
